### ISSUE TITLE
[Feature Request/Question] Recurse into Prompt possibleValues

### ISSUE THREAD

**Issue by hugeblank** [giann/sirocco#1]
So just by looking at your demonstration (and a tiny bit into the code) it's unclear if your `Prompt` module has the ability to recurse into the `possibleValues` table. What I could see you doing with this is autofilling based on what exists within the prompt. Here's an example
```
possibleValues = {
  this = {
    is = {
      a = {
        "demo",
        "test"
      },
      "SPARTA"
    },
    "that"
  },
  hey = {
    "there",
    "dude",
    "foo"
  }
}
```
So when the user inputs `t`, pressing tab would fill in `this`. If they continued, and pressed `i` then tab, `is` would fill in. And so on.

An additional feature on top of this would be to provide an option to add a character in additional to pressing `tab`, in this case it would be nice to fill in ` ` when the user tab-completes.

**Comment by giann** [comment]
Right now possibleValues is expected to be a flat number indexed table. I’ll consider your idea but I’m not sure in which use case it would be helpful ? Additionally if you want a “ “ suffixes after a completion you can just add it to each possible values.

**Comment by hugeblank** [comment]
The use case that I was thinking of was to format things like `_G`/`_ENV` into whatever you come up with so that it could be used for autofill (possibly for croissant? 😉).

WRT suffixes: valid :P

**Comment by giann** [comment]
Croissant does some completion based on the current token. More advanced completion requires to build an AST of the code in order to evaluate the correct expression before the cursor and search possible completion in it. In short, I’m on it :)
